import Head from "next/head";

import { useEffect } from "react";
import { userActions } from "../store/slices/management";
import { useDispatch, useSelector } from "react-redux";

import Navbar from "../components/Navbar";
import Header from "../components/Header";
import SectionSelect from "../components/SectionSelect";
import Modal from "../components/Modal";
import TermsConditions from "../components/TermsConditions";
import SocialSection from "../components/SocialSection";
import Footer from "../components/Footer";

export default function Home({ ui }) {
  const dispatch = useDispatch();
  const language = useSelector((state) => state.ui.language);
  const content = useSelector((state) => state.ui.content);

  useEffect(() => {
    dispatch(userActions.setUiContent(ui[language]));

    return () => {};
  }, [language]);

  if (Object.keys(content).length === 0) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Test Xcaret</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Modal />
      <main>
        <Navbar />
        <Header />
        <section>
          <SectionSelect />
          <SectionSelect swap={true} />
          <SectionSelect />
        </section>
        <section>
          <TermsConditions />
        </section>
        <section>
          <SocialSection />
        </section>
      </main>
      <Footer />
    </>
  );
}

export async function getStaticProps() {
  try {
    const data = await fetch(
      `https://raw.githubusercontent.com/javialcocer/test-json/main/data.json`
    );
    const json = await data.json();
    return {
      props: { ui: json },
    };
  } catch (error) {
    return {
      props: { ui: "error en la peticion" },
    };
  }
}
